// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef PROTOBUF_msg_2eproto__INCLUDED
#define PROTOBUF_msg_2eproto__INCLUDED

#include <string>

#include "../../../l3lib/include/google/protobuf/stubs/common.h"

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include "../../../l3lib/include/google/protobuf/arena.h"
#include "../../../l3lib/include/google/protobuf/arenastring.h"
#include "../../../l3lib/include/google/protobuf/generated_message_util.h"
#include "../../../l3lib/include/google/protobuf/metadata.h"
#include "../../../l3lib/include/google/protobuf/message.h"
#include "../../../l3lib/include/google/protobuf/repeated_field.h"
#include "../../../l3lib/include/google/protobuf/extension_set.h"
#include "../../../l3lib/include/google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_msg_2eproto();
void protobuf_AssignDesc_msg_2eproto();
void protobuf_ShutdownFile_msg_2eproto();

class MsgBody;
class MsgHead;
class OrdinaryResponse;

// ===================================================================

class MsgHead : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MsgHead) */ {
 public:
  MsgHead();
  virtual ~MsgHead();

  MsgHead(const MsgHead& from);

  inline MsgHead& operator=(const MsgHead& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgHead& default_instance();

  void Swap(MsgHead* other);

  // implements Message ----------------------------------------------

  inline MsgHead* New() const { return New(NULL); }

  MsgHead* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgHead& from);
  void MergeFrom(const MsgHead& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional fixed32 cmd = 1;
  void clear_cmd();
  static const int kCmdFieldNumber = 1;
  ::google::protobuf::uint32 cmd() const;
  void set_cmd(::google::protobuf::uint32 value);

  // optional fixed32 msgbody_len = 2;
  void clear_msgbody_len();
  static const int kMsgbodyLenFieldNumber = 2;
  ::google::protobuf::uint32 msgbody_len() const;
  void set_msgbody_len(::google::protobuf::uint32 value);

  // optional fixed32 seq = 3;
  void clear_seq();
  static const int kSeqFieldNumber = 3;
  ::google::protobuf::uint32 seq() const;
  void set_seq(::google::protobuf::uint32 value);

  // optional fixed32 checksum = 4;
  void clear_checksum();
  static const int kChecksumFieldNumber = 4;
  ::google::protobuf::uint32 checksum() const;
  void set_checksum(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MsgHead)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 cmd_;
  ::google::protobuf::uint32 msgbody_len_;
  ::google::protobuf::uint32 seq_;
  ::google::protobuf::uint32 checksum_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_msg_2eproto();
  friend void protobuf_AssignDesc_msg_2eproto();
  friend void protobuf_ShutdownFile_msg_2eproto();

  void InitAsDefaultInstance();
  static MsgHead* default_instance_;
};
// -------------------------------------------------------------------

class MsgBody : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MsgBody) */ {
 public:
  MsgBody();
  virtual ~MsgBody();

  MsgBody(const MsgBody& from);

  inline MsgBody& operator=(const MsgBody& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgBody& default_instance();

  void Swap(MsgBody* other);

  // implements Message ----------------------------------------------

  inline MsgBody* New() const { return New(NULL); }

  MsgBody* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgBody& from);
  void MergeFrom(const MsgBody& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgBody* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes body = 1;
  void clear_body();
  static const int kBodyFieldNumber = 1;
  const ::std::string& body() const;
  void set_body(const ::std::string& value);
  void set_body(const char* value);
  void set_body(const void* value, size_t size);
  ::std::string* mutable_body();
  ::std::string* release_body();
  void set_allocated_body(::std::string* body);

  // optional uint64 session_id = 2;
  void clear_session_id();
  static const int kSessionIdFieldNumber = 2;
  ::google::protobuf::uint64 session_id() const;
  void set_session_id(::google::protobuf::uint64 value);

  // optional string session = 3;
  void clear_session();
  static const int kSessionFieldNumber = 3;
  const ::std::string& session() const;
  void set_session(const ::std::string& value);
  void set_session(const char* value);
  void set_session(const char* value, size_t size);
  ::std::string* mutable_session();
  ::std::string* release_session();
  void set_allocated_session(::std::string* session);

  // optional bytes additional = 4;
  void clear_additional();
  static const int kAdditionalFieldNumber = 4;
  const ::std::string& additional() const;
  void set_additional(const ::std::string& value);
  void set_additional(const char* value);
  void set_additional(const void* value, size_t size);
  ::std::string* mutable_additional();
  ::std::string* release_additional();
  void set_allocated_additional(::std::string* additional);

  // optional string sbody = 5;
  void clear_sbody();
  static const int kSbodyFieldNumber = 5;
  const ::std::string& sbody() const;
  void set_sbody(const ::std::string& value);
  void set_sbody(const char* value);
  void set_sbody(const char* value, size_t size);
  ::std::string* mutable_sbody();
  ::std::string* release_sbody();
  void set_allocated_sbody(::std::string* sbody);

  // @@protoc_insertion_point(class_scope:MsgBody)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr body_;
  ::google::protobuf::uint64 session_id_;
  ::google::protobuf::internal::ArenaStringPtr session_;
  ::google::protobuf::internal::ArenaStringPtr additional_;
  ::google::protobuf::internal::ArenaStringPtr sbody_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_msg_2eproto();
  friend void protobuf_AssignDesc_msg_2eproto();
  friend void protobuf_ShutdownFile_msg_2eproto();

  void InitAsDefaultInstance();
  static MsgBody* default_instance_;
};
// -------------------------------------------------------------------

class OrdinaryResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OrdinaryResponse) */ {
 public:
  OrdinaryResponse();
  virtual ~OrdinaryResponse();

  OrdinaryResponse(const OrdinaryResponse& from);

  inline OrdinaryResponse& operator=(const OrdinaryResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrdinaryResponse& default_instance();

  void Swap(OrdinaryResponse* other);

  // implements Message ----------------------------------------------

  inline OrdinaryResponse* New() const { return New(NULL); }

  OrdinaryResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrdinaryResponse& from);
  void MergeFrom(const OrdinaryResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OrdinaryResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 err_no = 1;
  void clear_err_no();
  static const int kErrNoFieldNumber = 1;
  ::google::protobuf::int32 err_no() const;
  void set_err_no(::google::protobuf::int32 value);

  // optional bytes err_msg = 2;
  void clear_err_msg();
  static const int kErrMsgFieldNumber = 2;
  const ::std::string& err_msg() const;
  void set_err_msg(const ::std::string& value);
  void set_err_msg(const char* value);
  void set_err_msg(const void* value, size_t size);
  ::std::string* mutable_err_msg();
  ::std::string* release_err_msg();
  void set_allocated_err_msg(::std::string* err_msg);

  // @@protoc_insertion_point(class_scope:OrdinaryResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr err_msg_;
  ::google::protobuf::int32 err_no_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_msg_2eproto();
  friend void protobuf_AssignDesc_msg_2eproto();
  friend void protobuf_ShutdownFile_msg_2eproto();

  void InitAsDefaultInstance();
  static OrdinaryResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgHead

// optional fixed32 cmd = 1;
inline void MsgHead::clear_cmd() {
  cmd_ = 0u;
}
inline ::google::protobuf::uint32 MsgHead::cmd() const {
  // @@protoc_insertion_point(field_get:MsgHead.cmd)
  return cmd_;
}
inline void MsgHead::set_cmd(::google::protobuf::uint32 value) {
  
  cmd_ = value;
  // @@protoc_insertion_point(field_set:MsgHead.cmd)
}

// optional fixed32 msgbody_len = 2;
inline void MsgHead::clear_msgbody_len() {
  msgbody_len_ = 0u;
}
inline ::google::protobuf::uint32 MsgHead::msgbody_len() const {
  // @@protoc_insertion_point(field_get:MsgHead.msgbody_len)
  return msgbody_len_;
}
inline void MsgHead::set_msgbody_len(::google::protobuf::uint32 value) {
  
  msgbody_len_ = value;
  // @@protoc_insertion_point(field_set:MsgHead.msgbody_len)
}

// optional fixed32 seq = 3;
inline void MsgHead::clear_seq() {
  seq_ = 0u;
}
inline ::google::protobuf::uint32 MsgHead::seq() const {
  // @@protoc_insertion_point(field_get:MsgHead.seq)
  return seq_;
}
inline void MsgHead::set_seq(::google::protobuf::uint32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:MsgHead.seq)
}

// optional fixed32 checksum = 4;
inline void MsgHead::clear_checksum() {
  checksum_ = 0u;
}
inline ::google::protobuf::uint32 MsgHead::checksum() const {
  // @@protoc_insertion_point(field_get:MsgHead.checksum)
  return checksum_;
}
inline void MsgHead::set_checksum(::google::protobuf::uint32 value) {
  
  checksum_ = value;
  // @@protoc_insertion_point(field_set:MsgHead.checksum)
}

// -------------------------------------------------------------------

// MsgBody

// optional bytes body = 1;
inline void MsgBody::clear_body() {
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MsgBody::body() const {
  // @@protoc_insertion_point(field_get:MsgBody.body)
  return body_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_body(const ::std::string& value) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgBody.body)
}
inline void MsgBody::set_body(const char* value) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgBody.body)
}
inline void MsgBody::set_body(const void* value, size_t size) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgBody.body)
}
inline ::std::string* MsgBody::mutable_body() {
  
  // @@protoc_insertion_point(field_mutable:MsgBody.body)
  return body_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgBody::release_body() {
  // @@protoc_insertion_point(field_release:MsgBody.body)
  
  return body_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_allocated_body(::std::string* body) {
  if (body != NULL) {
    
  } else {
    
  }
  body_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body);
  // @@protoc_insertion_point(field_set_allocated:MsgBody.body)
}

// optional uint64 session_id = 2;
inline void MsgBody::clear_session_id() {
  session_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MsgBody::session_id() const {
  // @@protoc_insertion_point(field_get:MsgBody.session_id)
  return session_id_;
}
inline void MsgBody::set_session_id(::google::protobuf::uint64 value) {
  
  session_id_ = value;
  // @@protoc_insertion_point(field_set:MsgBody.session_id)
}

// optional string session = 3;
inline void MsgBody::clear_session() {
  session_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MsgBody::session() const {
  // @@protoc_insertion_point(field_get:MsgBody.session)
  return session_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_session(const ::std::string& value) {
  
  session_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgBody.session)
}
inline void MsgBody::set_session(const char* value) {
  
  session_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgBody.session)
}
inline void MsgBody::set_session(const char* value, size_t size) {
  
  session_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgBody.session)
}
inline ::std::string* MsgBody::mutable_session() {
  
  // @@protoc_insertion_point(field_mutable:MsgBody.session)
  return session_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgBody::release_session() {
  // @@protoc_insertion_point(field_release:MsgBody.session)
  
  return session_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_allocated_session(::std::string* session) {
  if (session != NULL) {
    
  } else {
    
  }
  session_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session);
  // @@protoc_insertion_point(field_set_allocated:MsgBody.session)
}

// optional bytes additional = 4;
inline void MsgBody::clear_additional() {
  additional_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MsgBody::additional() const {
  // @@protoc_insertion_point(field_get:MsgBody.additional)
  return additional_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_additional(const ::std::string& value) {
  
  additional_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgBody.additional)
}
inline void MsgBody::set_additional(const char* value) {
  
  additional_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgBody.additional)
}
inline void MsgBody::set_additional(const void* value, size_t size) {
  
  additional_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgBody.additional)
}
inline ::std::string* MsgBody::mutable_additional() {
  
  // @@protoc_insertion_point(field_mutable:MsgBody.additional)
  return additional_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgBody::release_additional() {
  // @@protoc_insertion_point(field_release:MsgBody.additional)
  
  return additional_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_allocated_additional(::std::string* additional) {
  if (additional != NULL) {
    
  } else {
    
  }
  additional_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), additional);
  // @@protoc_insertion_point(field_set_allocated:MsgBody.additional)
}

// optional string sbody = 5;
inline void MsgBody::clear_sbody() {
  sbody_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MsgBody::sbody() const {
  // @@protoc_insertion_point(field_get:MsgBody.sbody)
  return sbody_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_sbody(const ::std::string& value) {
  
  sbody_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgBody.sbody)
}
inline void MsgBody::set_sbody(const char* value) {
  
  sbody_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgBody.sbody)
}
inline void MsgBody::set_sbody(const char* value, size_t size) {
  
  sbody_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgBody.sbody)
}
inline ::std::string* MsgBody::mutable_sbody() {
  
  // @@protoc_insertion_point(field_mutable:MsgBody.sbody)
  return sbody_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgBody::release_sbody() {
  // @@protoc_insertion_point(field_release:MsgBody.sbody)
  
  return sbody_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_allocated_sbody(::std::string* sbody) {
  if (sbody != NULL) {
    
  } else {
    
  }
  sbody_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sbody);
  // @@protoc_insertion_point(field_set_allocated:MsgBody.sbody)
}

// -------------------------------------------------------------------

// OrdinaryResponse

// optional int32 err_no = 1;
inline void OrdinaryResponse::clear_err_no() {
  err_no_ = 0;
}
inline ::google::protobuf::int32 OrdinaryResponse::err_no() const {
  // @@protoc_insertion_point(field_get:OrdinaryResponse.err_no)
  return err_no_;
}
inline void OrdinaryResponse::set_err_no(::google::protobuf::int32 value) {
  
  err_no_ = value;
  // @@protoc_insertion_point(field_set:OrdinaryResponse.err_no)
}

// optional bytes err_msg = 2;
inline void OrdinaryResponse::clear_err_msg() {
  err_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OrdinaryResponse::err_msg() const {
  // @@protoc_insertion_point(field_get:OrdinaryResponse.err_msg)
  return err_msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OrdinaryResponse::set_err_msg(const ::std::string& value) {
  
  err_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OrdinaryResponse.err_msg)
}
inline void OrdinaryResponse::set_err_msg(const char* value) {
  
  err_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OrdinaryResponse.err_msg)
}
inline void OrdinaryResponse::set_err_msg(const void* value, size_t size) {
  
  err_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OrdinaryResponse.err_msg)
}
inline ::std::string* OrdinaryResponse::mutable_err_msg() {
  
  // @@protoc_insertion_point(field_mutable:OrdinaryResponse.err_msg)
  return err_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OrdinaryResponse::release_err_msg() {
  // @@protoc_insertion_point(field_release:OrdinaryResponse.err_msg)
  
  return err_msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OrdinaryResponse::set_allocated_err_msg(::std::string* err_msg) {
  if (err_msg != NULL) {
    
  } else {
    
  }
  err_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), err_msg);
  // @@protoc_insertion_point(field_set_allocated:OrdinaryResponse.err_msg)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_2eproto__INCLUDED
