// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef PROTOBUF_INCLUDED_msg_2eproto
#define PROTOBUF_INCLUDED_msg_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_msg_2eproto 

namespace protobuf_msg_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_msg_2eproto
class MsgBody;
class MsgBodyDefaultTypeInternal;
extern MsgBodyDefaultTypeInternal _MsgBody_default_instance_;
class MsgBody_Response;
class MsgBody_ResponseDefaultTypeInternal;
extern MsgBody_ResponseDefaultTypeInternal _MsgBody_Response_default_instance_;
class MsgHead;
class MsgHeadDefaultTypeInternal;
extern MsgHeadDefaultTypeInternal _MsgHead_default_instance_;
class OrdinaryResponse;
class OrdinaryResponseDefaultTypeInternal;
extern OrdinaryResponseDefaultTypeInternal _OrdinaryResponse_default_instance_;
namespace google {
namespace protobuf {
template<> ::MsgBody* Arena::CreateMaybeMessage<::MsgBody>(Arena*);
template<> ::MsgBody_Response* Arena::CreateMaybeMessage<::MsgBody_Response>(Arena*);
template<> ::MsgHead* Arena::CreateMaybeMessage<::MsgHead>(Arena*);
template<> ::OrdinaryResponse* Arena::CreateMaybeMessage<::OrdinaryResponse>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class OrdinaryResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OrdinaryResponse) */ {
 public:
  OrdinaryResponse();
  virtual ~OrdinaryResponse();

  OrdinaryResponse(const OrdinaryResponse& from);

  inline OrdinaryResponse& operator=(const OrdinaryResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OrdinaryResponse(OrdinaryResponse&& from) noexcept
    : OrdinaryResponse() {
    *this = ::std::move(from);
  }

  inline OrdinaryResponse& operator=(OrdinaryResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrdinaryResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OrdinaryResponse* internal_default_instance() {
    return reinterpret_cast<const OrdinaryResponse*>(
               &_OrdinaryResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(OrdinaryResponse* other);
  friend void swap(OrdinaryResponse& a, OrdinaryResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OrdinaryResponse* New() const final {
    return CreateMaybeMessage<OrdinaryResponse>(NULL);
  }

  OrdinaryResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<OrdinaryResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const OrdinaryResponse& from);
  void MergeFrom(const OrdinaryResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OrdinaryResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes err_msg = 2;
  bool has_err_msg() const;
  void clear_err_msg();
  static const int kErrMsgFieldNumber = 2;
  const ::std::string& err_msg() const;
  void set_err_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_err_msg(::std::string&& value);
  #endif
  void set_err_msg(const char* value);
  void set_err_msg(const void* value, size_t size);
  ::std::string* mutable_err_msg();
  ::std::string* release_err_msg();
  void set_allocated_err_msg(::std::string* err_msg);

  // optional int32 err_no = 1;
  bool has_err_no() const;
  void clear_err_no();
  static const int kErrNoFieldNumber = 1;
  ::google::protobuf::int32 err_no() const;
  void set_err_no(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:OrdinaryResponse)
 private:
  void set_has_err_no();
  void clear_has_err_no();
  void set_has_err_msg();
  void clear_has_err_msg();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr err_msg_;
  ::google::protobuf::int32 err_no_;
  friend struct ::protobuf_msg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MsgHead : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MsgHead) */ {
 public:
  MsgHead();
  virtual ~MsgHead();

  MsgHead(const MsgHead& from);

  inline MsgHead& operator=(const MsgHead& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MsgHead(MsgHead&& from) noexcept
    : MsgHead() {
    *this = ::std::move(from);
  }

  inline MsgHead& operator=(MsgHead&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgHead& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgHead* internal_default_instance() {
    return reinterpret_cast<const MsgHead*>(
               &_MsgHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(MsgHead* other);
  friend void swap(MsgHead& a, MsgHead& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MsgHead* New() const final {
    return CreateMaybeMessage<MsgHead>(NULL);
  }

  MsgHead* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MsgHead>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MsgHead& from);
  void MergeFrom(const MsgHead& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required fixed32 cmd = 1;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 1;
  ::google::protobuf::uint32 cmd() const;
  void set_cmd(::google::protobuf::uint32 value);

  // required fixed32 msgbody_len = 2;
  bool has_msgbody_len() const;
  void clear_msgbody_len();
  static const int kMsgbodyLenFieldNumber = 2;
  ::google::protobuf::uint32 msgbody_len() const;
  void set_msgbody_len(::google::protobuf::uint32 value);

  // required fixed32 seq = 3;
  bool has_seq() const;
  void clear_seq();
  static const int kSeqFieldNumber = 3;
  ::google::protobuf::uint32 seq() const;
  void set_seq(::google::protobuf::uint32 value);

  // required fixed32 checksum = 4;
  bool has_checksum() const;
  void clear_checksum();
  static const int kChecksumFieldNumber = 4;
  ::google::protobuf::uint32 checksum() const;
  void set_checksum(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MsgHead)
 private:
  void set_has_cmd();
  void clear_has_cmd();
  void set_has_msgbody_len();
  void clear_has_msgbody_len();
  void set_has_seq();
  void clear_has_seq();
  void set_has_checksum();
  void clear_has_checksum();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 cmd_;
  ::google::protobuf::uint32 msgbody_len_;
  ::google::protobuf::uint32 seq_;
  ::google::protobuf::uint32 checksum_;
  friend struct ::protobuf_msg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MsgBody_Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MsgBody.Response) */ {
 public:
  MsgBody_Response();
  virtual ~MsgBody_Response();

  MsgBody_Response(const MsgBody_Response& from);

  inline MsgBody_Response& operator=(const MsgBody_Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MsgBody_Response(MsgBody_Response&& from) noexcept
    : MsgBody_Response() {
    *this = ::std::move(from);
  }

  inline MsgBody_Response& operator=(MsgBody_Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgBody_Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgBody_Response* internal_default_instance() {
    return reinterpret_cast<const MsgBody_Response*>(
               &_MsgBody_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(MsgBody_Response* other);
  friend void swap(MsgBody_Response& a, MsgBody_Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MsgBody_Response* New() const final {
    return CreateMaybeMessage<MsgBody_Response>(NULL);
  }

  MsgBody_Response* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MsgBody_Response>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MsgBody_Response& from);
  void MergeFrom(const MsgBody_Response& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgBody_Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes msg = 2;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const void* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // optional int32 code = 1;
  bool has_code() const;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MsgBody.Response)
 private:
  void set_has_code();
  void clear_has_code();
  void set_has_msg();
  void clear_has_msg();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 code_;
  friend struct ::protobuf_msg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MsgBody : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MsgBody) */ {
 public:
  MsgBody();
  virtual ~MsgBody();

  MsgBody(const MsgBody& from);

  inline MsgBody& operator=(const MsgBody& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MsgBody(MsgBody&& from) noexcept
    : MsgBody() {
    *this = ::std::move(from);
  }

  inline MsgBody& operator=(MsgBody&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgBody& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgBody* internal_default_instance() {
    return reinterpret_cast<const MsgBody*>(
               &_MsgBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(MsgBody* other);
  friend void swap(MsgBody& a, MsgBody& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MsgBody* New() const final {
    return CreateMaybeMessage<MsgBody>(NULL);
  }

  MsgBody* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MsgBody>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MsgBody& from);
  void MergeFrom(const MsgBody& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgBody* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef MsgBody_Response Response;

  // accessors -------------------------------------------------------

  // optional bytes body = 1;
  bool has_body() const;
  void clear_body();
  static const int kBodyFieldNumber = 1;
  const ::std::string& body() const;
  void set_body(const ::std::string& value);
  #if LANG_CXX11
  void set_body(::std::string&& value);
  #endif
  void set_body(const char* value);
  void set_body(const void* value, size_t size);
  ::std::string* mutable_body();
  ::std::string* release_body();
  void set_allocated_body(::std::string* body);

  // optional string sbody = 2;
  bool has_sbody() const;
  void clear_sbody();
  static const int kSbodyFieldNumber = 2;
  const ::std::string& sbody() const;
  void set_sbody(const ::std::string& value);
  #if LANG_CXX11
  void set_sbody(::std::string&& value);
  #endif
  void set_sbody(const char* value);
  void set_sbody(const char* value, size_t size);
  ::std::string* mutable_sbody();
  ::std::string* release_sbody();
  void set_allocated_sbody(::std::string* sbody);

  // optional string session = 4;
  bool has_session() const;
  void clear_session();
  static const int kSessionFieldNumber = 4;
  const ::std::string& session() const;
  void set_session(const ::std::string& value);
  #if LANG_CXX11
  void set_session(::std::string&& value);
  #endif
  void set_session(const char* value);
  void set_session(const char* value, size_t size);
  ::std::string* mutable_session();
  ::std::string* release_session();
  void set_allocated_session(::std::string* session);

  // optional bytes additional = 5;
  bool has_additional() const;
  void clear_additional();
  static const int kAdditionalFieldNumber = 5;
  const ::std::string& additional() const;
  void set_additional(const ::std::string& value);
  #if LANG_CXX11
  void set_additional(::std::string&& value);
  #endif
  void set_additional(const char* value);
  void set_additional(const void* value, size_t size);
  ::std::string* mutable_additional();
  ::std::string* release_additional();
  void set_allocated_additional(::std::string* additional);

  // optional string trace_id = 6;
  bool has_trace_id() const;
  void clear_trace_id();
  static const int kTraceIdFieldNumber = 6;
  const ::std::string& trace_id() const;
  void set_trace_id(const ::std::string& value);
  #if LANG_CXX11
  void set_trace_id(::std::string&& value);
  #endif
  void set_trace_id(const char* value);
  void set_trace_id(const char* value, size_t size);
  ::std::string* mutable_trace_id();
  ::std::string* release_trace_id();
  void set_allocated_trace_id(::std::string* trace_id);

  // optional .MsgBody.Response rsp_result = 7;
  bool has_rsp_result() const;
  void clear_rsp_result();
  static const int kRspResultFieldNumber = 7;
  private:
  const ::MsgBody_Response& _internal_rsp_result() const;
  public:
  const ::MsgBody_Response& rsp_result() const;
  ::MsgBody_Response* release_rsp_result();
  ::MsgBody_Response* mutable_rsp_result();
  void set_allocated_rsp_result(::MsgBody_Response* rsp_result);

  // optional uint32 session_id = 3;
  bool has_session_id() const;
  void clear_session_id();
  static const int kSessionIdFieldNumber = 3;
  ::google::protobuf::uint32 session_id() const;
  void set_session_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MsgBody)
 private:
  void set_has_body();
  void clear_has_body();
  void set_has_sbody();
  void clear_has_sbody();
  void set_has_session_id();
  void clear_has_session_id();
  void set_has_session();
  void clear_has_session();
  void set_has_additional();
  void clear_has_additional();
  void set_has_trace_id();
  void clear_has_trace_id();
  void set_has_rsp_result();
  void clear_has_rsp_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr body_;
  ::google::protobuf::internal::ArenaStringPtr sbody_;
  ::google::protobuf::internal::ArenaStringPtr session_;
  ::google::protobuf::internal::ArenaStringPtr additional_;
  ::google::protobuf::internal::ArenaStringPtr trace_id_;
  ::MsgBody_Response* rsp_result_;
  ::google::protobuf::uint32 session_id_;
  friend struct ::protobuf_msg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OrdinaryResponse

// optional int32 err_no = 1;
inline bool OrdinaryResponse::has_err_no() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrdinaryResponse::set_has_err_no() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrdinaryResponse::clear_has_err_no() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrdinaryResponse::clear_err_no() {
  err_no_ = 0;
  clear_has_err_no();
}
inline ::google::protobuf::int32 OrdinaryResponse::err_no() const {
  // @@protoc_insertion_point(field_get:OrdinaryResponse.err_no)
  return err_no_;
}
inline void OrdinaryResponse::set_err_no(::google::protobuf::int32 value) {
  set_has_err_no();
  err_no_ = value;
  // @@protoc_insertion_point(field_set:OrdinaryResponse.err_no)
}

// optional bytes err_msg = 2;
inline bool OrdinaryResponse::has_err_msg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrdinaryResponse::set_has_err_msg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrdinaryResponse::clear_has_err_msg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrdinaryResponse::clear_err_msg() {
  err_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_err_msg();
}
inline const ::std::string& OrdinaryResponse::err_msg() const {
  // @@protoc_insertion_point(field_get:OrdinaryResponse.err_msg)
  return err_msg_.GetNoArena();
}
inline void OrdinaryResponse::set_err_msg(const ::std::string& value) {
  set_has_err_msg();
  err_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OrdinaryResponse.err_msg)
}
#if LANG_CXX11
inline void OrdinaryResponse::set_err_msg(::std::string&& value) {
  set_has_err_msg();
  err_msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:OrdinaryResponse.err_msg)
}
#endif
inline void OrdinaryResponse::set_err_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_err_msg();
  err_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OrdinaryResponse.err_msg)
}
inline void OrdinaryResponse::set_err_msg(const void* value, size_t size) {
  set_has_err_msg();
  err_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OrdinaryResponse.err_msg)
}
inline ::std::string* OrdinaryResponse::mutable_err_msg() {
  set_has_err_msg();
  // @@protoc_insertion_point(field_mutable:OrdinaryResponse.err_msg)
  return err_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OrdinaryResponse::release_err_msg() {
  // @@protoc_insertion_point(field_release:OrdinaryResponse.err_msg)
  if (!has_err_msg()) {
    return NULL;
  }
  clear_has_err_msg();
  return err_msg_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OrdinaryResponse::set_allocated_err_msg(::std::string* err_msg) {
  if (err_msg != NULL) {
    set_has_err_msg();
  } else {
    clear_has_err_msg();
  }
  err_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), err_msg);
  // @@protoc_insertion_point(field_set_allocated:OrdinaryResponse.err_msg)
}

// -------------------------------------------------------------------

// MsgHead

// required fixed32 cmd = 1;
inline bool MsgHead::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgHead::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgHead::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgHead::clear_cmd() {
  cmd_ = 0u;
  clear_has_cmd();
}
inline ::google::protobuf::uint32 MsgHead::cmd() const {
  // @@protoc_insertion_point(field_get:MsgHead.cmd)
  return cmd_;
}
inline void MsgHead::set_cmd(::google::protobuf::uint32 value) {
  set_has_cmd();
  cmd_ = value;
  // @@protoc_insertion_point(field_set:MsgHead.cmd)
}

// required fixed32 msgbody_len = 2;
inline bool MsgHead::has_msgbody_len() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgHead::set_has_msgbody_len() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgHead::clear_has_msgbody_len() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgHead::clear_msgbody_len() {
  msgbody_len_ = 0u;
  clear_has_msgbody_len();
}
inline ::google::protobuf::uint32 MsgHead::msgbody_len() const {
  // @@protoc_insertion_point(field_get:MsgHead.msgbody_len)
  return msgbody_len_;
}
inline void MsgHead::set_msgbody_len(::google::protobuf::uint32 value) {
  set_has_msgbody_len();
  msgbody_len_ = value;
  // @@protoc_insertion_point(field_set:MsgHead.msgbody_len)
}

// required fixed32 seq = 3;
inline bool MsgHead::has_seq() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgHead::set_has_seq() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgHead::clear_has_seq() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgHead::clear_seq() {
  seq_ = 0u;
  clear_has_seq();
}
inline ::google::protobuf::uint32 MsgHead::seq() const {
  // @@protoc_insertion_point(field_get:MsgHead.seq)
  return seq_;
}
inline void MsgHead::set_seq(::google::protobuf::uint32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:MsgHead.seq)
}

// required fixed32 checksum = 4;
inline bool MsgHead::has_checksum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgHead::set_has_checksum() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgHead::clear_has_checksum() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgHead::clear_checksum() {
  checksum_ = 0u;
  clear_has_checksum();
}
inline ::google::protobuf::uint32 MsgHead::checksum() const {
  // @@protoc_insertion_point(field_get:MsgHead.checksum)
  return checksum_;
}
inline void MsgHead::set_checksum(::google::protobuf::uint32 value) {
  set_has_checksum();
  checksum_ = value;
  // @@protoc_insertion_point(field_set:MsgHead.checksum)
}

// -------------------------------------------------------------------

// MsgBody_Response

// optional int32 code = 1;
inline bool MsgBody_Response::has_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgBody_Response::set_has_code() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgBody_Response::clear_has_code() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgBody_Response::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 MsgBody_Response::code() const {
  // @@protoc_insertion_point(field_get:MsgBody.Response.code)
  return code_;
}
inline void MsgBody_Response::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:MsgBody.Response.code)
}

// optional bytes msg = 2;
inline bool MsgBody_Response::has_msg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgBody_Response::set_has_msg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgBody_Response::clear_has_msg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgBody_Response::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msg();
}
inline const ::std::string& MsgBody_Response::msg() const {
  // @@protoc_insertion_point(field_get:MsgBody.Response.msg)
  return msg_.GetNoArena();
}
inline void MsgBody_Response::set_msg(const ::std::string& value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgBody.Response.msg)
}
#if LANG_CXX11
inline void MsgBody_Response::set_msg(::std::string&& value) {
  set_has_msg();
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.Response.msg)
}
#endif
inline void MsgBody_Response::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgBody.Response.msg)
}
inline void MsgBody_Response::set_msg(const void* value, size_t size) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgBody.Response.msg)
}
inline ::std::string* MsgBody_Response::mutable_msg() {
  set_has_msg();
  // @@protoc_insertion_point(field_mutable:MsgBody.Response.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgBody_Response::release_msg() {
  // @@protoc_insertion_point(field_release:MsgBody.Response.msg)
  if (!has_msg()) {
    return NULL;
  }
  clear_has_msg();
  return msg_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody_Response::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:MsgBody.Response.msg)
}

// -------------------------------------------------------------------

// MsgBody

// optional bytes body = 1;
inline bool MsgBody::has_body() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgBody::set_has_body() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgBody::clear_has_body() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgBody::clear_body() {
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_body();
}
inline const ::std::string& MsgBody::body() const {
  // @@protoc_insertion_point(field_get:MsgBody.body)
  return body_.GetNoArena();
}
inline void MsgBody::set_body(const ::std::string& value) {
  set_has_body();
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgBody.body)
}
#if LANG_CXX11
inline void MsgBody::set_body(::std::string&& value) {
  set_has_body();
  body_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.body)
}
#endif
inline void MsgBody::set_body(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_body();
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgBody.body)
}
inline void MsgBody::set_body(const void* value, size_t size) {
  set_has_body();
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgBody.body)
}
inline ::std::string* MsgBody::mutable_body() {
  set_has_body();
  // @@protoc_insertion_point(field_mutable:MsgBody.body)
  return body_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgBody::release_body() {
  // @@protoc_insertion_point(field_release:MsgBody.body)
  if (!has_body()) {
    return NULL;
  }
  clear_has_body();
  return body_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_allocated_body(::std::string* body) {
  if (body != NULL) {
    set_has_body();
  } else {
    clear_has_body();
  }
  body_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body);
  // @@protoc_insertion_point(field_set_allocated:MsgBody.body)
}

// optional string sbody = 2;
inline bool MsgBody::has_sbody() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgBody::set_has_sbody() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgBody::clear_has_sbody() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgBody::clear_sbody() {
  sbody_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sbody();
}
inline const ::std::string& MsgBody::sbody() const {
  // @@protoc_insertion_point(field_get:MsgBody.sbody)
  return sbody_.GetNoArena();
}
inline void MsgBody::set_sbody(const ::std::string& value) {
  set_has_sbody();
  sbody_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgBody.sbody)
}
#if LANG_CXX11
inline void MsgBody::set_sbody(::std::string&& value) {
  set_has_sbody();
  sbody_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.sbody)
}
#endif
inline void MsgBody::set_sbody(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_sbody();
  sbody_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgBody.sbody)
}
inline void MsgBody::set_sbody(const char* value, size_t size) {
  set_has_sbody();
  sbody_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgBody.sbody)
}
inline ::std::string* MsgBody::mutable_sbody() {
  set_has_sbody();
  // @@protoc_insertion_point(field_mutable:MsgBody.sbody)
  return sbody_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgBody::release_sbody() {
  // @@protoc_insertion_point(field_release:MsgBody.sbody)
  if (!has_sbody()) {
    return NULL;
  }
  clear_has_sbody();
  return sbody_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_allocated_sbody(::std::string* sbody) {
  if (sbody != NULL) {
    set_has_sbody();
  } else {
    clear_has_sbody();
  }
  sbody_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sbody);
  // @@protoc_insertion_point(field_set_allocated:MsgBody.sbody)
}

// optional uint32 session_id = 3;
inline bool MsgBody::has_session_id() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MsgBody::set_has_session_id() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MsgBody::clear_has_session_id() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MsgBody::clear_session_id() {
  session_id_ = 0u;
  clear_has_session_id();
}
inline ::google::protobuf::uint32 MsgBody::session_id() const {
  // @@protoc_insertion_point(field_get:MsgBody.session_id)
  return session_id_;
}
inline void MsgBody::set_session_id(::google::protobuf::uint32 value) {
  set_has_session_id();
  session_id_ = value;
  // @@protoc_insertion_point(field_set:MsgBody.session_id)
}

// optional string session = 4;
inline bool MsgBody::has_session() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgBody::set_has_session() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgBody::clear_has_session() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgBody::clear_session() {
  session_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_session();
}
inline const ::std::string& MsgBody::session() const {
  // @@protoc_insertion_point(field_get:MsgBody.session)
  return session_.GetNoArena();
}
inline void MsgBody::set_session(const ::std::string& value) {
  set_has_session();
  session_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgBody.session)
}
#if LANG_CXX11
inline void MsgBody::set_session(::std::string&& value) {
  set_has_session();
  session_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.session)
}
#endif
inline void MsgBody::set_session(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_session();
  session_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgBody.session)
}
inline void MsgBody::set_session(const char* value, size_t size) {
  set_has_session();
  session_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgBody.session)
}
inline ::std::string* MsgBody::mutable_session() {
  set_has_session();
  // @@protoc_insertion_point(field_mutable:MsgBody.session)
  return session_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgBody::release_session() {
  // @@protoc_insertion_point(field_release:MsgBody.session)
  if (!has_session()) {
    return NULL;
  }
  clear_has_session();
  return session_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_allocated_session(::std::string* session) {
  if (session != NULL) {
    set_has_session();
  } else {
    clear_has_session();
  }
  session_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session);
  // @@protoc_insertion_point(field_set_allocated:MsgBody.session)
}

// optional bytes additional = 5;
inline bool MsgBody::has_additional() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgBody::set_has_additional() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgBody::clear_has_additional() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgBody::clear_additional() {
  additional_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_additional();
}
inline const ::std::string& MsgBody::additional() const {
  // @@protoc_insertion_point(field_get:MsgBody.additional)
  return additional_.GetNoArena();
}
inline void MsgBody::set_additional(const ::std::string& value) {
  set_has_additional();
  additional_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgBody.additional)
}
#if LANG_CXX11
inline void MsgBody::set_additional(::std::string&& value) {
  set_has_additional();
  additional_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.additional)
}
#endif
inline void MsgBody::set_additional(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_additional();
  additional_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgBody.additional)
}
inline void MsgBody::set_additional(const void* value, size_t size) {
  set_has_additional();
  additional_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgBody.additional)
}
inline ::std::string* MsgBody::mutable_additional() {
  set_has_additional();
  // @@protoc_insertion_point(field_mutable:MsgBody.additional)
  return additional_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgBody::release_additional() {
  // @@protoc_insertion_point(field_release:MsgBody.additional)
  if (!has_additional()) {
    return NULL;
  }
  clear_has_additional();
  return additional_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_allocated_additional(::std::string* additional) {
  if (additional != NULL) {
    set_has_additional();
  } else {
    clear_has_additional();
  }
  additional_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), additional);
  // @@protoc_insertion_point(field_set_allocated:MsgBody.additional)
}

// optional string trace_id = 6;
inline bool MsgBody::has_trace_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgBody::set_has_trace_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgBody::clear_has_trace_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgBody::clear_trace_id() {
  trace_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_trace_id();
}
inline const ::std::string& MsgBody::trace_id() const {
  // @@protoc_insertion_point(field_get:MsgBody.trace_id)
  return trace_id_.GetNoArena();
}
inline void MsgBody::set_trace_id(const ::std::string& value) {
  set_has_trace_id();
  trace_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MsgBody.trace_id)
}
#if LANG_CXX11
inline void MsgBody::set_trace_id(::std::string&& value) {
  set_has_trace_id();
  trace_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.trace_id)
}
#endif
inline void MsgBody::set_trace_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_trace_id();
  trace_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MsgBody.trace_id)
}
inline void MsgBody::set_trace_id(const char* value, size_t size) {
  set_has_trace_id();
  trace_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MsgBody.trace_id)
}
inline ::std::string* MsgBody::mutable_trace_id() {
  set_has_trace_id();
  // @@protoc_insertion_point(field_mutable:MsgBody.trace_id)
  return trace_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgBody::release_trace_id() {
  // @@protoc_insertion_point(field_release:MsgBody.trace_id)
  if (!has_trace_id()) {
    return NULL;
  }
  clear_has_trace_id();
  return trace_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgBody::set_allocated_trace_id(::std::string* trace_id) {
  if (trace_id != NULL) {
    set_has_trace_id();
  } else {
    clear_has_trace_id();
  }
  trace_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), trace_id);
  // @@protoc_insertion_point(field_set_allocated:MsgBody.trace_id)
}

// optional .MsgBody.Response rsp_result = 7;
inline bool MsgBody::has_rsp_result() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsgBody::set_has_rsp_result() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsgBody::clear_has_rsp_result() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsgBody::clear_rsp_result() {
  if (rsp_result_ != NULL) rsp_result_->Clear();
  clear_has_rsp_result();
}
inline const ::MsgBody_Response& MsgBody::_internal_rsp_result() const {
  return *rsp_result_;
}
inline const ::MsgBody_Response& MsgBody::rsp_result() const {
  const ::MsgBody_Response* p = rsp_result_;
  // @@protoc_insertion_point(field_get:MsgBody.rsp_result)
  return p != NULL ? *p : *reinterpret_cast<const ::MsgBody_Response*>(
      &::_MsgBody_Response_default_instance_);
}
inline ::MsgBody_Response* MsgBody::release_rsp_result() {
  // @@protoc_insertion_point(field_release:MsgBody.rsp_result)
  clear_has_rsp_result();
  ::MsgBody_Response* temp = rsp_result_;
  rsp_result_ = NULL;
  return temp;
}
inline ::MsgBody_Response* MsgBody::mutable_rsp_result() {
  set_has_rsp_result();
  if (rsp_result_ == NULL) {
    auto* p = CreateMaybeMessage<::MsgBody_Response>(GetArenaNoVirtual());
    rsp_result_ = p;
  }
  // @@protoc_insertion_point(field_mutable:MsgBody.rsp_result)
  return rsp_result_;
}
inline void MsgBody::set_allocated_rsp_result(::MsgBody_Response* rsp_result) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete rsp_result_;
  }
  if (rsp_result) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      rsp_result = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, rsp_result, submessage_arena);
    }
    set_has_rsp_result();
  } else {
    clear_has_rsp_result();
  }
  rsp_result_ = rsp_result;
  // @@protoc_insertion_point(field_set_allocated:MsgBody.rsp_result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_msg_2eproto
